language: python
python:
  - "2.7"

# install python dependencies including this package in the travis
# virtualenv
install:
  - pip install -r requirements/python-dev

# commands to run the testing suite. if any of these fail, travic lets us know
script:
  - python webdev/manage.py test webdev/django_scrubadub
  - pep8 --exclude=migrations django_scrubadub/
  # - cd docs && make html && cd -
